import { DocumentTypeDefinition } from "@/types/document";

/**
 * Phase 2 document types. Metadata only — no fields/template yet.
 * Each one only needs a fields[] array + defaultTemplate string to
 * become fully functional; the generator, preview, and PDF export
 * already work generically off DocumentTypeDefinition.
 */
export const comingSoonDocuments: DocumentTypeDefinition[] = [
  {
    id: "employment-agreement",
    name: "Employment Agreement",
    shortName: "Employment Agreement",
    description: "Detailed long-form employment contract.",
    category: "Legal",
    icon: "FileText",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
  {
    id: "internship-agreement",
    name: "Internship Agreement",
    shortName: "Internship Agreement",
    description: "Legal agreement accompanying an internship offer.",
    category: "Legal",
    icon: "FileText",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
  {
    id: "experience-letter",
    name: "Experience Letter",
    shortName: "Experience Letter",
    description: "Summarizes an employee's role, tenure, and performance.",
    category: "Offboarding",
    icon: "Award",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
  {
    id: "warning-letter",
    name: "Warning Letter",
    shortName: "Warning Letter",
    description: "Formal notice regarding conduct or performance concerns.",
    category: "Performance",
    icon: "AlertTriangle",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
  {
    id: "promotion-letter",
    name: "Promotion Letter",
    shortName: "Promotion Letter",
    description: "Confirms a role, title, or compensation upgrade.",
    category: "Performance",
    icon: "TrendingUp",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
  {
    id: "salary-revision",
    name: "Salary Revision Letter",
    shortName: "Salary Revision",
    description: "Communicates an updated compensation structure.",
    category: "Performance",
    icon: "IndianRupee",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
  {
    id: "confirmation-letter",
    name: "Confirmation Letter",
    shortName: "Confirmation Letter",
    description: "Confirms an employee's permanent status post-probation.",
    category: "Performance",
    icon: "BadgeCheck",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
  {
    id: "internship-completion",
    name: "Internship Completion Certificate",
    shortName: "Internship Certificate",
    description: "Certifies successful completion of an internship.",
    category: "Offboarding",
    icon: "ScrollText",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
  {
    id: "employment-verification",
    name: "Employment Verification Letter",
    shortName: "Employment Verification",
    description: "Confirms employment status for external verification requests.",
    category: "Verification",
    icon: "BadgeCheck",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
  {
    id: "recommendation-letter",
    name: "Recommendation Letter",
    shortName: "Recommendation Letter",
    description: "Personal or professional recommendation for an employee.",
    category: "Verification",
    icon: "ThumbsUp",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
  {
    id: "background-verification-consent",
    name: "Background Verification Consent",
    shortName: "BGV Consent",
    description: "Candidate consent form authorizing a background check.",
    category: "Verification",
    icon: "ShieldCheck",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
  {
    id: "reference-check-form",
    name: "Reference Check Form",
    shortName: "Reference Check",
    description: "Structured form for capturing a referee's feedback.",
    category: "Verification",
    icon: "ClipboardList",
    available: false,
    fields: [],
    defaultTemplate: "",
  },
];
